//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasingEntry
    {
        public int PurchasingEntryId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> MedicineId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
